---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None

---
apiVersion: v1
kind: Service
metadata:
  name: rocketchat-service
spec:
  selector:
    app: rocketchat
  ports:
    - name: rocketchat-ui
      port: 3000
      targetPort: 30050
      nodePort: 30050
  type: LoadBalancer

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  serviceName: mongodb
  replicas: 3
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongodb
          image: mongo
          command:
          - mongod
          - "--bind_ip_all"
          - "--replSet"
          - rs0
          ports:
            - containerPort: 27017
      volumes:
        - name: mongodb-volume
          persistentVolumeClaim:
            claimName: mongodb-claim
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketchat-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocketchat
  template:
    metadata:
      labels:
        app: rocketchat
    spec:
      containers:
        - name: rocketchat
          image: rocketchat/rocket.chat:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: mongodb://mongodb-deployment-0.mongodb:27017/rocketchat
            - name: MONGO_OPLOG_URL
              value: mongodb://mongodb-deployment-0.mongodb:27017/local?replSet=rs0
          imagePullPolicy: Always
