---
- name: Initialize the Kubernetes cluster using kubeadm
  command: >-
    kubeadm init
    --apiserver-advertise-address="192.168.60.10"
    --apiserver-cert-extra-sans="192.168.60.10"
    --node-name master
    --pod-network-cidr=192.168.0.0/16

- name: Setup kubeconfig for vagrant user
  command: "{{ item }}"
  with_items:
    - mkdir -p /home/vagrant/.kube
    - cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
    - chown vagrant:vagrant /home/vagrant/.kube/config

- name: Install calico pod operator
  become: false
  command: >-
    kubectl create -f
    https://raw.githubusercontent.com/projectcalico/calico/v3.24.1/manifests/tigera-operator.yaml

- name: Install calico pod config
  become: false
  command: >-
    kubectl create -f
    https://raw.githubusercontent.com/projectcalico/calico/v3.24.1/manifests/custom-resources.yaml

- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command

- name: Copy join command to local file
  become: false
  local_action: >
    copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"
